from pathlib import Path
import json

root = Path('.')

def replace_once(rel, old, new, label):
    p = root / rel
    text = p.read_text()
    if old not in text:
        raise SystemExit(f'{label}: target not found')
    p.write_text(text.replace(old, new, 1))

replace_once('js/firefox-page.js', '''  let playButton = null\n  let stopButton = null\n  let statusNode = null\n  let rateInput = null\n''', '''  let playButton = null\n  let rateInput = null\n  let committedRate = 1\n''', 'controller state')

replace_once('js/firefox-page.js', '''  if (api.storage && api.storage.onChanged) {\n    api.storage.onChanged.addListener((changes, areaName) => {\n      if (areaName !== "local" || !changes.rate || !rateInput || !rateInput.isConnected) return\n      if (shadow && shadow.activeElement === rateInput) return\n      rateInput.value = formatReadAloudRate(changes.rate.newValue == null ? 1 : changes.rate.newValue)\n    })\n  }\n''', '''  if (api.storage && api.storage.onChanged) {\n    api.storage.onChanged.addListener((changes, areaName) => {\n      if (areaName !== "local" || !changes.rate) return\n      committedRate = normalizeReadAloudRate(changes.rate.newValue == null ? 1 : changes.rate.newValue)\n      if (!rateInput || !rateInput.isConnected) return\n      if (shadow && shadow.activeElement === rateInput) return\n      rateInput.value = formatReadAloudRate(committedRate)\n    })\n  }\n''', 'storage sync')

replace_once('js/firefox-page.js', '''      button:hover { background: rgba(255, 255, 255, .22); }\n      button:disabled { cursor: default; opacity: .55; }\n      .status { min-width: 58px; text-align: center; user-select: none; }\n      .rate-control {\n        display: flex;\n        align-items: center;\n        gap: 5px;\n        margin-left: 2px;\n      }\n      .rate-label {\n        color: rgba(255, 255, 255, .78);\n        user-select: none;\n      }\n      .rate-button {\n''', '''      button:hover { background: rgba(255, 255, 255, .22); }\n      button:disabled { cursor: default; opacity: .55; }\n      .rate-button {\n''', 'controller css labels')

old = '''    stopButton = document.createElement("button")\n    stopButton.type = "button"\n    stopButton.title = "Stop reading"\n    stopButton.setAttribute("aria-label", "Stop read aloud")\n    stopButton.textContent = "■"\n    stopButton.addEventListener("click", event => {\n      event.preventDefault()\n      event.stopPropagation()\n      send("pageStop").catch(() => {})\n    })\n\n    statusNode = document.createElement("span")\n    statusNode.className = "status"\n    statusNode.textContent = "Reading"\n\n    const rateControl = document.createElement("span")\n    rateControl.className = "rate-control"\n\n    const rateLabel = document.createElement("span")\n    rateLabel.className = "rate-label"\n    rateLabel.textContent = "Speed"\n\n    const decreaseRateButton = document.createElement("button")\n    decreaseRateButton.type = "button"\n    decreaseRateButton.className = "rate-button"\n    decreaseRateButton.title = "Decrease speed by 0.25"\n    decreaseRateButton.setAttribute("aria-label", "Decrease speech speed by 0.25")\n    decreaseRateButton.textContent = "−"\n    decreaseRateButton.addEventListener("click", event => {\n      event.preventDefault()\n      event.stopPropagation()\n      adjustReadAloudRate(-0.25)\n    })\n\n    rateInput = document.createElement("input")\n    rateInput.type = "text"\n    rateInput.inputMode = "decimal"\n    rateInput.className = "rate-input"\n    rateInput.title = "Speech speed multiplier"\n    rateInput.setAttribute("aria-label", "Speech speed multiplier")\n    rateInput.autocomplete = "off"\n    rateInput.spellcheck = false\n    rateInput.addEventListener("input", onReadAloudRateInput)\n    rateInput.addEventListener("change", commitReadAloudRateInput)\n    rateInput.addEventListener("keydown", event => {\n      if (event.key === "Enter") {\n        event.preventDefault()\n        commitReadAloudRateInput()\n        rateInput.select()\n      }\n    })\n\n    const increaseRateButton = document.createElement("button")\n    increaseRateButton.type = "button"\n    increaseRateButton.className = "rate-button"\n    increaseRateButton.title = "Increase speed by 0.25"\n    increaseRateButton.setAttribute("aria-label", "Increase speech speed by 0.25")\n    increaseRateButton.textContent = "+"\n    increaseRateButton.addEventListener("click", event => {\n      event.preventDefault()\n      event.stopPropagation()\n      adjustReadAloudRate(0.25)\n    })\n\n    rateControl.append(rateLabel, decreaseRateButton, rateInput, increaseRateButton)\n    panel.append(playButton, stopButton, statusNode, rateControl)\n'''
new = '''    rateInput = document.createElement("input")\n    rateInput.type = "text"\n    rateInput.inputMode = "decimal"\n    rateInput.className = "rate-input"\n    rateInput.title = "Speech speed multiplier"\n    rateInput.setAttribute("aria-label", "Speech speed multiplier")\n    rateInput.autocomplete = "off"\n    rateInput.spellcheck = false\n    rateInput.addEventListener("input", onReadAloudRateInput)\n    rateInput.addEventListener("blur", commitReadAloudRateInput)\n\n    const decreaseRateButton = document.createElement("button")\n    decreaseRateButton.type = "button"\n    decreaseRateButton.className = "rate-button"\n    decreaseRateButton.title = "Decrease speed by 0.25"\n    decreaseRateButton.setAttribute("aria-label", "Decrease speech speed by 0.25")\n    decreaseRateButton.textContent = "−"\n    decreaseRateButton.addEventListener("click", event => {\n      event.preventDefault()\n      event.stopPropagation()\n      adjustReadAloudRate(-0.25)\n    })\n\n    const increaseRateButton = document.createElement("button")\n    increaseRateButton.type = "button"\n    increaseRateButton.className = "rate-button"\n    increaseRateButton.title = "Increase speed by 0.25"\n    increaseRateButton.setAttribute("aria-label", "Increase speech speed by 0.25")\n    increaseRateButton.textContent = "+"\n    increaseRateButton.addEventListener("click", event => {\n      event.preventDefault()\n      event.stopPropagation()\n      adjustReadAloudRate(0.25)\n    })\n\n    panel.append(playButton, rateInput, decreaseRateButton, increaseRateButton)\n'''
replace_once('js/firefox-page.js', old, new, 'controller controls')

old = '''  function loadControllerRate() {\n    return api.storage.local.get("rate")\n      .then(settings => {\n        if (rateInput && (!shadow || shadow.activeElement !== rateInput)) {\n          rateInput.value = formatReadAloudRate(settings.rate == null ? 1 : settings.rate)\n        }\n      })\n      .catch(() => {})\n  }\n\n  function adjustReadAloudRate(delta) {\n    if (!rateInput) return\n    const current = Number(rateInput.value.trim())\n    if (Number.isFinite(current)) {\n      applyReadAloudRate(current + delta)\n      return\n    }\n    api.storage.local.get("rate")\n      .then(settings => applyReadAloudRate((settings.rate == null ? 1 : Number(settings.rate)) + delta))\n      .catch(() => {})\n  }\n\n  function onReadAloudRateInput() {\n    if (!rateInput) return\n    const value = Number(rateInput.value.trim())\n    if (Number.isFinite(value) && value >= .1 && value <= 10) {\n      send("setReadAloudRate", value).catch(() => {})\n    }\n  }\n\n  function commitReadAloudRateInput() {\n    if (!rateInput) return\n    const value = Number(rateInput.value.trim())\n    applyReadAloudRate(Number.isFinite(value) ? value : 1)\n  }\n\n  function applyReadAloudRate(value) {\n    if (!rateInput) return\n    const rate = normalizeReadAloudRate(value)\n    rateInput.value = formatReadAloudRate(rate)\n    send("setReadAloudRate", rate).catch(() => {})\n  }\n'''
new = '''  function loadControllerRate() {\n    return api.storage.local.get("rate")\n      .then(settings => {\n        committedRate = normalizeReadAloudRate(settings.rate == null ? 1 : settings.rate)\n        if (rateInput && (!shadow || shadow.activeElement !== rateInput)) {\n          rateInput.value = formatReadAloudRate(committedRate)\n        }\n      })\n      .catch(() => {})\n  }\n\n  function adjustReadAloudRate(delta) {\n    if (!rateInput) return\n    const current = Number(rateInput.value.trim())\n    applyReadAloudRate((Number.isFinite(current) ? current : committedRate) + delta)\n  }\n\n  function onReadAloudRateInput() {\n    if (!rateInput) return\n    const raw = rateInput.value\n    const caret = rateInput.selectionStart == null ? raw.length : rateInput.selectionStart\n    const cleaned = sanitizeReadAloudRateText(raw)\n    if (cleaned === raw) return\n    const cleanedBeforeCaret = sanitizeReadAloudRateText(raw.slice(0, caret))\n    rateInput.value = cleaned\n    try { rateInput.setSelectionRange(cleanedBeforeCaret.length, cleanedBeforeCaret.length) }\n    catch (err) {}\n  }\n\n  function sanitizeReadAloudRateText(value) {\n    let cleaned = String(value || "").replace(/[^0-9.]/g, "")\n    const dotIndex = cleaned.indexOf(".")\n    if (dotIndex >= 0) {\n      cleaned = cleaned.slice(0, dotIndex + 1) + cleaned.slice(dotIndex + 1).replace(/\\./g, "")\n    }\n    return cleaned\n  }\n\n  function commitReadAloudRateInput() {\n    if (!rateInput) return\n    const value = Number(rateInput.value.trim())\n    if (!Number.isFinite(value)) {\n      rateInput.value = formatReadAloudRate(committedRate)\n      return\n    }\n    applyReadAloudRate(value)\n  }\n\n  function applyReadAloudRate(value) {\n    if (!rateInput) return\n    const rate = normalizeReadAloudRate(value)\n    rateInput.value = formatReadAloudRate(rate)\n    if (rate === committedRate) return\n    committedRate = rate\n    send("setReadAloudRate", rate).catch(() => loadControllerRate())\n  }\n'''
replace_once('js/firefox-page.js', old, new, 'rate behavior')

replace_once('js/firefox-page.js', '''  function updateController(state) {\n    if (!playButton || !statusNode) return\n    if (state === "PLAYING") {\n      playButton.disabled = false\n      playButton.textContent = "❚❚"\n      playButton.title = "Pause"\n      playButton.setAttribute("aria-label", "Pause read aloud")\n      statusNode.textContent = "Reading"\n    }\n    else if (state === "PAUSED") {\n      playButton.disabled = false\n      playButton.textContent = "▶"\n      playButton.title = "Play"\n      playButton.setAttribute("aria-label", "Resume read aloud")\n      statusNode.textContent = "Paused"\n    }\n    else if (state === "LOADING") {\n      playButton.disabled = true\n      playButton.textContent = "…"\n      statusNode.textContent = "Loading"\n    }\n    else {\n      playButton.disabled = true\n      playButton.textContent = "▶"\n      statusNode.textContent = "Stopped"\n    }\n  }\n''', '''  function updateController(state) {\n    if (!playButton) return\n    if (state === "PLAYING") {\n      playButton.disabled = false\n      playButton.textContent = "❚❚"\n      playButton.title = "Pause"\n      playButton.setAttribute("aria-label", "Pause read aloud")\n    }\n    else if (state === "PAUSED") {\n      playButton.disabled = false\n      playButton.textContent = "▶"\n      playButton.title = "Play"\n      playButton.setAttribute("aria-label", "Resume read aloud")\n    }\n    else if (state === "LOADING") {\n      playButton.disabled = true\n      playButton.textContent = "…"\n      playButton.title = "Loading"\n      playButton.setAttribute("aria-label", "Read aloud loading")\n    }\n    else {\n      playButton.disabled = true\n      playButton.textContent = "▶"\n      playButton.title = "Stopped"\n      playButton.setAttribute("aria-label", "Read aloud stopped")\n    }\n  }\n''', 'controller status')

replace_once('js/firefox-page.js', '''    host = shadow = playButton = stopButton = statusNode = rateInput = highlight = null\n''', '''    host = shadow = playButton = rateInput = highlight = null\n''', 'inactive cleanup')

manifest = root / 'manifest.json'
data = json.loads(manifest.read_text())
if data.get('version') != '1.81.17':
    raise SystemExit(f"expected 1.81.17, got {data.get('version')}")
data['version'] = '1.81.18'
manifest.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
